name: Build

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine

    steps:
      - name: Install dependencies
        run: |
          apk add --update alpine-sdk linux-headers git zlib-dev libressl-dev gperf cmake ninja
      - uses: actions/checkout@v2
        with:
          repository: tdlib/telegram-bot-api
          submodules: recursive
      - name: Build
        env:
          CMAKE_GENERATOR: Ninja
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
          cmake --build . --target install
      - name: Package
        run: |
          cd build
          wget https://github.com/codehz/EasyPak/releases/download/v0.5.0/ezbin
          chmod +x ezbin
          mkdir lib
          lld bin/telegram-bot-api | tail -n +2 | awk '{ print $3 }' | while read line; do cp $line lib; done
          ./ezbin api <(
          cat <<EOF
          mktmpfs /tmp
          mktmpfs /tmp/tmp
          mkdir /tmp/root
          bind .:/tmp/root
          env HOME=/root
          chroot /tmp
          chdir /bin
          @bin
          chdir /lib
          @lib
          chdir /root
          exec-passthru /bin/telegram-bot-api
          EOF
          )
      - name: Upload artifact for inspect
        uses: actions/upload-artifact@v2.3.1
        with:
          name: inspect
          path: api
