name: Build

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine

    steps:
      - name: Install dependencies
        run: |
          apk add --update alpine-sdk linux-headers git zlib-dev libressl-dev gperf cmake ninja
      - uses: actions/checkout@v2
        with:
          repository: tdlib/telegram-bot-api
          submodules: recursive
      - name: Build
        env:
          CMAKE_GENERATOR: Ninja
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
          cmake --build . --target install
      - name: Upload artifact for inspect
        uses: actions/upload-artifact@v2.3.1
        with:
          name: inspect
          path: bin
